spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lms
    username: postgres
    password: alirida165
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

feign:
  client:
    cms:
      url: http://localhost:8084/api/transaction
    email:
      url: http://localhost:8083/api/email
