spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: alirida165hammoud@gmail.com
    password: cmwubhllidqonams
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
  mail.properties.mail.smtp.connectiontimeout: 5000
  mail.properties.mail.smtp.timeout: 5000
  mail.properties.mail.smtp.writetimeout: 5000

logging:
  level:
    org.springframework.mail: DEBUG
